import day11._

val input = """...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."""

val expandedInput = """....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#......."""

val expandedWithIds = """....1........
.........2...
3............
.............
.............
........4....
.5...........
............6
.............
.............
.........7...
8....9......."""

class Day11Suite extends munit.FunSuite {
  test("string representation matches") {
    val image = Day11.toImage(input.linesIterator)
    assertEquals(input, image.toString())
  }

  test("expansion matches") {
    val image = Day11.toImage(input.linesIterator)
    val expandedImage = Day11.toImage(expandedInput.linesIterator)
    assertEquals(image.intoExpanded, expandedImage)
  }
}
